services:
  traffic:
    image: grafana/k6
    command: run /traffic/normal-traffic.js
    volumes:
      - ./traffic:/traffic:ro
    environment:
      - TARGET=${TARGET:-http://localhost:8080}
    networks:
      - defender_proxy-network

networks:
  defender_proxy-network:
    external: true